# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-15 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('hours', models.PositiveSmallIntegerField()),
                ('course_type', models.CharField(choices=[('MA', '전공 필수'), ('EL', '전공 선택')], max_length=2, null=True)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Area')),
            ],
        ),
        migrations.CreateModel(
            name='CourseAcquired',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired_type', models.CharField(choices=[('CU', '교양'), ('MA', '전공 필수'), ('EL', '전공 선택')], max_length=2, null=True)),
                ('major_type', models.CharField(choices=[('MA', '주전공'), ('MI', '부전공'), ('DM', '복수전공')], max_length=2, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_type', models.CharField(choices=[('MA', '주전공'), ('MI', '부전공'), ('DM', '복수전공')], default='MA', max_length=2)),
                ('rule_type', models.CharField(choices=[('AR', '영역'), ('CO', '과목'), ('CU', '임의')], max_length=2)),
                ('value_type', models.CharField(choices=[('HO', '학점수'), ('CO', '과목수')], max_length=2)),
                ('value', models.PositiveSmallIntegerField()),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Area')),
                ('courses', models.ManyToManyField(to='core.Course')),
                ('dept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Department')),
            ],
        ),
    ]
