# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-04 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('year', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('hours', models.PositiveSmallIntegerField()),
                ('area', models.CharField(max_length=40)),
                ('subarea', models.CharField(max_length=40)),
            ],
        ),
    ]
