# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-16 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseacquired',
            name='acquired_type',
            field=models.CharField(choices=[('CU', '교양'), ('MA', '전공 필수'), ('EL', '전공 선택'), ('NL', '일반 선택')], max_length=2, null=True),
        ),
    ]
