# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-16 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160516_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='scope_from',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='scope_to',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
